{
    "name":        "Catalogix Digital",
    "version":     "19.0.1.0.0",
    "summary":     "Módulo de catálogo digital para Catalogix",
    "author":      "Catalogix",
    "category":    "Sales/Catalog",
    "depends":     ["base", "sale", "product", "website", "account", "mail", "stock"],
    "data": [
        "security/vendor_groups.xml",
        "security/model_catalog_customer.xml",
        "security/model_catalog_inventory_movement.xml",
        "security/model_catalog_pricing.xml",
        "security/model_catalog_review.xml",
        "security/ir.model.access.csv",
        "views/catalog_views.xml",
        "views/vendor_views.xml",
        "views/customer_views.xml",
        "views/product_views.xml",
        "views/pricing_views.xml",
        "views/audit_views.xml",
        "views/promotion_views.xml",
        "views/review_views.xml",
        "views/notification_views.xml",
        "data/catalog_data.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application":  True,
}
