[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
db_host = db
db_port = 5432
db_user = odoo
db_password = 12345678
db_name = catalogix
admin_passwd = $pbkdf2-sha512$600000$hdBai1EKgXDOOYfQeg8B4A$qpUpM4vT072HntbFUcA0yi9PAqLF/DogSa.y5ip7gRoFGatAoIk.aDvfOqqV0okRq18Zi3Ek1y4tbw9Zmwem0Q
http_port = 8069
http_interface = 0.0.0.0
log_level = info
init = base

